version: "3.8"

networks:
  vali:

services:

  grafana:
    image: ghcr.io/credativ/plutono:7.3.4
    ports:
      - "3000:3000"
    networks:
      - vali

  valitail:
    image: ghcr.io/credativ/valitail:2.0.0
    volumes:
      - /var/log:/var/log
      - ./config:/etc/valitail/
    ports:
      - "9080:9080"
    command: -config.file=/etc/valitail/valitail-gateway.yaml
    networks:
      - vali

  vali-gateway:
    image: nginx:1.19
    volumes:
      - ./config/nginx-vali-gateway.conf:/etc/nginx/nginx.conf
    ports:
      - "80"
      - "3100"
    networks:
      - vali

  vali-frontend:
    image: ghcr.io/credativ/vali:2.0.0
    volumes:
        - ./config:/etc/vali/
    ports:
        - "3100"
    command: "-config.file=/etc/vali/vali-docker-memberlist-boltdb-shipper.yaml -target=query-frontend"
    networks:
      - vali
    deploy:
      mode: replicated
      replicas: 2

  vali-1:
    image: ghcr.io/credativ/vali:2.0.0
    volumes:
      - ./config:/etc/vali/
      - ./chunks:/vali/chunks/
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/vali/vali-docker-memberlist-boltdb-shipper.yaml -target=all"
    networks:
      - vali
    restart: on-failure

  vali-2:
    image: ghcr.io/credativ/vali:2.0.0
    volumes:
      - ./config:/etc/vali/
      - ./chunks:/vali/chunks/
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/vali/vali-docker-memberlist-boltdb-shipper.yaml -target=all"
    # command: "-config.file=/etc/vali/vali-config.yaml"
    networks:
      - vali
    restart: on-failure

  vali-3:
    image: ghcr.io/credativ/vali:2.0.0
    volumes:
      - ./config:/etc/vali/
      - ./chunks:/vali/chunks/
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/vali/vali-docker-memberlist-boltdb-shipper.yaml -target=all"
    # command: "-config.file=/etc/vali/vali-config.yaml"
    networks:
      - vali
    restart: on-failure
